apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sdk-metadata-search-service
  description: Search Service of the Superb Data Kraken
  annotations:
    dev.azure.com/project-repo: EFS-SDK/search
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - spring-boot
    - sdk
    - sdk-metadata
  links:
    - url: https://sdk.efs.ai/sdk-frontend/apps/search
      title: e:fs SDK (prod) Frontend Search
    - url: https://sdk-dev.efs.ai/sdk-frontend/apps/search
      title: e:fs SDK (dev) Frontend Search
    - url: https://aicloud.efs.ai/sdk-frontend/apps/search
      title: AICloud (prod) Frontend Search
    - url: https://sdk.efs.ai/search/swagger-ui/index.html
      title: e:fs SDK (prod) Swagger UI
    - url: https://sdk-dev.efs.ai/search/swagger-ui/index.html
      title: e:fs SDK (dev) Swagger UI
    - url: https://aicloud.efs.ai/search/swagger-ui/index.html
      title: AICloud (prod) Swagger UI
spec:
  type: service
  lifecycle: production
  owner: team-sdk
  system: sdk
  subcomponentOf: sdk-metadata
  dependsOn:
    - component:sdk-metadata-opensearch-service
    - component:sdk-operations-keycloak-service
    - component:sdk-schema-manager-service
  providesApis:
    - sdk-metadata-search-api
  consumesApis:
    - sdk-metadata-opensearch-api
    - sdk-operations-keycloak-api
    - sdk-metadata-schemamanager-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sdk-metadata-search-api
  description: Search Api of the Superb Data Kraken
  annotations:
    dev.azure.com/project-repo: EFS-SDK/search
  tags:
    - sdk
    - sdk-metadata
  links:
    - url: https://sdk.efs.ai/search/swagger-ui/index.html
      title: e:fs SDK (prod) Swagger UI
    - url: https://sdk-dev.efs.ai/search/swagger-ui/index.html
      title: e:fs SDK (dev) Swagger UI
    - url: https://aicloud.efs.ai/search/swagger-ui/index.html
      title: AICloud (prod) Swagger UI
spec:
  type: openapi
  lifecycle: production
  owner: team-sdk
  system: sdk
  definition:
    $text: https://sdk.efs.ai/search/v3/api-docs