apiVersion: v1
kind: ConfigMap
metadata:
  name: search
  namespace: backend
data:
  application.yml: |-
    apidoc:
      title: EFS SDK Search-API
    sdk:
      oauth2:
        config-url: http://keycloak$(postfix)-http.operations.svc.cluster.local/auth/realms/efs-$(environment)/.well-known/openid-configuration
        client-id: $(environment)-client
        authorization-grant-type: authorization_code
        scope: openid
        user-name-attribute: preferred_username
    server:
      port: 8090
      servlet:
        context-path: /search
    search:
      elasticsearch:
        url: https://$(elasticsearch-service).elasticsearch.svc.cluster.local:9200
    management:
      endpoints:
        web:
          exposure:
            include: [
                prometheus,
                health,
                info
            ]
      health:
        elasticsearch:
          enabled: false