apiVersion: v1
kind: ConfigMap
metadata:
  name: search
  namespace: backend
data:
  application.yml: |-
    apidoc:
      title: EFS SDK Search-API
    sdk:
      oauth2:
        config-url: http://keycloak$(postfix)-http.operations.svc.cluster.local/auth/realms/$(REALM)/.well-known/openid-configuration
        client-id: $(CLIENT_ID)
        authorization-grant-type: authorization_code
        scope: openid
        user-name-attribute: preferred_username
    server:
      port: 8090
      servlet:
        context-path: /search
    search:
      elasticsearch:
        url: https://$(ELASTICSEARCH_SERVICE).elasticsearch.svc.cluster.local:9200
      organizationmanager-endpoints:
        spaces: http://organizationmanager$(postfix).backend.svc.cluster.local:8090/organizationmanager/api/v2.0/spaces
    management:
      endpoints:
        web:
          exposure:
            include: [
              prometheus,
              health,
              info
            ]
      health:
        elasticsearch:
          enabled: false
